jobs:
  lint:
    name: Linter
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 18.x
    - continue-on-error: true
      run: yarn
    - continue-on-error: true
      run: yarn validate:eslint
  tsc:
    name: TypeScript
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        cache: yarn
        node-version: 18.x
    - continue-on-error: true
      run: yarn
    - continue-on-error: true
      run: yarn validate:typescript
name: Validate
on:
  repository_dispatch:
    types: trigger-ga___validate.yaml
